---
title: "Review"
subtitle: "Course Review and Exam Prep"
author: "Dr Cillian McHugh"
institute: "PS4168: Economic Psychology"
bibliography: "resources/bib/My Library.bib"
csl: apa.csl
format: 
  revealjs:
    slide-number: false
    controls: true
    logo: "resources/images/ul-psychology-logos.png"
    footer: "PS4168: Cillian McHugh - 29/11/24"
    theme: "resources/css/mytheme.scss"
    incremental: false
    chalkboard: 
      buttons: true
editor: source
---

## Overview

- Review, Reflection, Discussion
- Exam Prep


## Topics: ([link here](https://docs.google.com/document/d/1iBG-SDrUpJX1RtsfmynqL8WY9git7VfaZvMuuhAGJ0I/edit?usp=sharing))


:::: {.columns}

::: {.column width="45%"}
General Introduction and History of Economic Psychology

Heuristics and Biases

Nudges and Other Contextual Influences

Theories of Decision Making

Game Theory


:::

::: {.column width="10%"}

:::

::: {.column width="45%"}
Emotional Influences Future Decisions and Affective Forecasting

Loss Aversion/Risk Aversion and Endowment Effects

Mental Accounting

Fairness and Ethics

Gambling
:::

::::

## Topics ([link here](https://docs.google.com/document/d/1iBG-SDrUpJX1RtsfmynqL8WY9git7VfaZvMuuhAGJ0I/edit?usp=sharing))

<iframe width="1102" height="600" src="https://docs.google.com/document/d/1iBG-SDrUpJX1RtsfmynqL8WY9git7VfaZvMuuhAGJ0I/edit?usp=sharing?embedded=true&rm=minimal" frameborder="0" ></iframe>

[https://docs.google.com/document/d/1iBG-SDrUpJX1RtsfmynqL8WY9git7VfaZvMuuhAGJ0I/edit?usp=sharing](https://docs.google.com/document/d/1iBG-SDrUpJX1RtsfmynqL8WY9git7VfaZvMuuhAGJ0I/edit?usp=sharing)


## Reflection and Discussion

- Identify $2$ - $3$ more general things that you learned as a result of taking this module?

- What was the most interesting thing you learned from this module and why?

- What would you change about this module?

## Potential Exam Questions{.smaller}


Select one of the statements below and critically discuss it with reference to content covered as part of this module (both in lectures, and your own reading)

 

- Human decision making cannot be understood independently of context
- When it comes to choice architecture, there is no such thing as neutral design
- Decision making is always influenced by loss aversion and risk aversion
- The role of emotions in decision making. 
- "our mental states or processes are rational when they help us to achieve our goals" [@over_rationality_2004, p. 3]. 



## Exam Grading

---------------------------------------------------------------------------------
Component                                                        Percentage
--------------------------------------------------------------- -----------------
Content                                                            70\% 

Structure, Language, and Written Expression                        30\% 

References, Citations, and Formatting                               0\% (potential penalty of 1 sub-grade)

---------------------------------------------------------------------------------

## Breakdown{.smaller}

*Content*

The assignment should directly address the question asked and demonstrate a clear coherent argument throughout.  Excessive descriptions should be avoided if they do not serve to support an argument.  Evidence of critical thinking is essential.  Students should demonstrate evidence of wider reading and understanding of the concepts being discussed.

*Stucture, Language, and Written Expression*

Ideas should be clearly expressed, with appropriate use of scientific language.  There should be a clear introduction, body, and conclusion, with appropriate use of paragraphs (The use of sub-headings is optional). 

*References, Citations, and Formatting*

In-text citations and the References section should be in APA style. All citations should appear in the References section, and all references should be cited in the text. A References section should be included.  




# References

## References

\noindent
\vspace{-2em}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{7.5pt}
